#!/bin/sh

mkdir -p /var/lib/service_weburl
lua -e 'require("service_weburl.db").init_db()'

uci -q batch <<-EOF >/dev/null
    delete ucitrack.@service_weburl[-1]
    add ucitrack service_weburl
    set ucitrack.@service_weburl[-1].init=service_weburl
    commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
